# Generated by Django 3.2.16 on 2024-05-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20240506_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs_images', verbose_name='Фото'),
        ),
    ]
