# Generated by Django 3.2.16 on 2024-05-10 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_profile_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
